---

    - name: Install pip
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - clangd-10
        state: present

    - name: Create a symbolic link from clangd-10 to clangd
      become: yes
      file:
        src: /usr/bin/clangd-10
        dest: /usr/bin/clangd
        state: link


    - name: Modify bashrc to add aliases for vim and vi
      blockinfile:
        path: "{{ LOCAL_DOT_CONFIG_PATH }}/nvim/init.vim"
        marker: "\" {mark} ANSIBLE MANAGED BLOCK [nvim-lsp-c]"
        block: |
            lua <<EOF
            require'lspconfig'.clangd.setup{}
            EOF
