---

    - name: Create a directory if it does not exist
      file:
        path: "{{ LOCAL_APPIMAGE_PATH }}"
        state: directory
        mode: '0755'

    - name: Create a directory if it does not exist
      file:
        path: "{{ LOCAL_BIN_PATH }}"
        state: directory
        mode: '0755'

    - name: Download Neovim
      get_url:
        url: "https://github.com/neovim/neovim/releases/download/v{{ NVIM_VERSION }}/nvim.appimage"
        dest: "{{ LOCAL_APPIMAGE_PATH }}/{{ APPIMAGE_FILENAME }}"
        mode: 0755

    - name: Create a symbolic link for neovim "{{ LOCAL_APPIMAGE_PATH }}/{{ APPIMAGE_FILENAME }}"
      file:
        src: "{{ LOCAL_APPIMAGE_PATH }}/{{ APPIMAGE_FILENAME }}"
        dest: "{{ LOCAL_BIN_PATH }}/nvim"
        state: link

    - name: Copy the nvim config directory to "{{ LOCAL_DOT_CONFIG_PATH }}"
      copy:
        src: nvim
        dest: "{{ LOCAL_DOT_CONFIG_PATH }}"

    - name: Create a directory [ "{{ LOCAL_DOT_CONFIG_PATH }}/autoload" ]
      file:
        path: "{{ LOCAL_DOT_CONFIG_PATH }}/nvim/autoload"
        state: directory
        mode: '0755'

    - name: Download Vim Plug ["{{ LOCAL_DOT_CONFIG_PATH }}/autoload/plug.vim"]
      get_url:
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
        dest: "{{ LOCAL_DOT_CONFIG_PATH }}/nvim/autoload/plug.vim"
        mode: 0755

    - name: Modify bashrc to add aliases for vim and vi
      blockinfile:
        path: "{{ HOME_USER_DIR }}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK [nvim]"
        create: True
        block: |
            alias vim=nvim
            alias vi=nvim

    - name: Install nvim plug plugins
      shell: nvim +PlugInstall +qall
