---

    - name: Create a directory if it does not exist
      file:
        path: "{{ LOCAL_APPIMAGE_PATH }}"
        state: directory
        mode: '0755'

    - name: Create a directory if it does not exist
      file:
        path: "{{ LOCAL_BIN_PATH }}"
        state: directory
        mode: '0755'

    - name: Download Neovim
      get_url:
        url: "https://github.com/neovim/neovim/releases/download/{{ NVIM_VERSION }}/nvim.appimage"
        dest: "{{ LOCAL_APPIMAGE_PATH }}/{{ APPIMAGE_FILENAME }}"
        mode: 0755

    - name: Create a symbolic link for neovim "{{ LOCAL_APPIMAGE_PATH }}/{{ APPIMAGE_FILENAME }}"
      file:
        src: "{{ LOCAL_APPIMAGE_PATH }}/{{ APPIMAGE_FILENAME }}"
        dest: "{{ LOCAL_BIN_PATH }}/nvim"
        state: link
    
    - name: Copy the nvim config directory to "{{ LOCAL_DOT_CONFIG_PATH }}"
      copy:
        src: nvim
        dest: "{{ LOCAL_DOT_CONFIG_PATH }}"

    - name: Modify bashrc to add aliases for vim and vi
      blockinfile:
        path: "{{ HOME_USER_DIR }}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK [nvim]"
        create: True
        block: |
            alias vim=nvim
            alias vi=nvim

