---

    - name: Create a directory if it does not exist
      file:
        path: "{{ LOCAL_APPIMAGE_PATH }}"
        state: directory
        mode: '0755'

    - name: Create a directory if it does not exist
      file:
        path: "{{ LOCAL_BIN_PATH }}"
        state: directory
        mode: '0755'

    - name: Install wl-clipboard
      become: true
      apt:
        name: wl-clipboard
        state: present
        update_cache: true

    - name: Download Neovim
      get_url:
        url: "https://github.com/neovim/neovim/releases/download/{{ NVIM_VERSION }}/nvim-linux-x86_64.appimage"
        dest: "{{ LOCAL_APPIMAGE_PATH }}/{{ APPIMAGE_FILENAME }}"
        mode: 0755

    - name: Create a symbolic link for neovim "{{ LOCAL_APPIMAGE_PATH }}/{{ APPIMAGE_FILENAME }}"
      file:
        src: "{{ LOCAL_APPIMAGE_PATH }}/{{ APPIMAGE_FILENAME }}"
        dest: "{{ LOCAL_BIN_PATH }}/nvim"
        state: link
    
    - name: Symlink nvim config to "{{ LOCAL_DOT_CONFIG_PATH }}"
      file:
        src: "{{ role_path }}/files/nvim"
        dest: "{{ LOCAL_DOT_CONFIG_PATH }}/nvim"
        state: link


    - name: Modify bashrc to add aliases for vim and vi
      blockinfile:
        path: "{{ HOME_USER_DIR }}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK [nvim]"
        create: True
        block: |
            vim() {
                if [ -n "$NVIM" ]; then
                    command nvim --server "$NVIM" --remote "$(realpath $@)"
                else
                    command nvim "$@"
                fi
            }
            
            vi() {
                if [ -n "$NVIM" ]; then
                    command nvim --server "$NVIM" --remote "$(realpath $@)"
                else
                    command nvim "$@"
                fi
            }
