---

    - name: Download tmux appimage
      get_url:
        url: "https://github.com/tmux/tmux/releases/download/{{ TMUX_VERSION }}/tmux-{{ TMUX_VERSION }}-x86_64.AppImage"
        dest: "{{ LOCAL_APPIMAGE_PATH }}/{{ APPIMAGE_FILENAME }}"
        mode: 0755

    - name: Create a symbolic link for tmux "{{ LOCAL_APPIMAGE_PATH }}/{{ APPIMAGE_FILENAME }}"
      file:
        src: "{{ LOCAL_APPIMAGE_PATH }}/{{ APPIMAGE_FILENAME }}"
        dest: "{{ LOCAL_BIN_PATH }}/tmux"
        state: link

    - name: Modify bashrc to add workaround for TERM and tmux app image
      blockinfile:
        path: "{{ HOME_USER_DIR }}/.bashrc"
        create: True
        block: |
            TERM=xterm


