---

    - name: Install pip
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name:
          - python3-pip
        state: present

    - name: Install the python language server
      pip:
        name:
          - python-language-server
          - pyflakes
          - pycodestyle

    - name: Install nvim plug plugins
      shell: nvim --headless +PlugInstall +qa

    - name: Modify bashrc to add aliases for vim and vi
      blockinfile:
        path: "{{ LOCAL_DOT_CONFIG_PATH }}/nvim/init.vim"
        marker: "\" {mark} ANSIBLE MANAGED BLOCK [nvim-lsp-python]"
        block: |
            lua <<EOF
            require'lspconfig'.pylsp.setup{
              on_attach=require'diagnostic'.on_attach;
              settings = {
                pyls = {
                  plugins = {
                    pycodestyle = {
                      enabled = true;
                      maxLineLength = 130;
                      }
                    }
                  }
                }
              }
            EOF
            autocmd Filetype python setlocal omnifunc=v:lua.vim.lsp.omnifunc
