---

    - name: Install the neovim remote
      pip:
        name:
          - neovim-remote
    
    - name: Modify bashrc - expand nvr with fzf completion 
      blockinfile:
        path: "{{ HOME_USER_DIR }}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK [nvr fzf]"
        create: True
        block: |
            _fzf_setup_completion path nvr
