---
# Create the needed dirs
    - name: Create the home dir for app images if not there
      file:
       path: "{{ LOCAL_APPIMAGE_PATH }}"
       state: directory
       mode: 0755

    - name: Create "{{ LOCAL_BIN_PATH }}" if not there
      file:
       path: "{{ LOCAL_BIN_PATH }}"
       state: directory
       mode: 0755
    
    - name: Create "{{ LOCAL_DOT_CONFIG_PATH }}" if not there
      file:
       path: "{{ LOCAL_DOT_CONFIG_PATH }}"
       state: directory
       mode: 0755

       # TODO: I'm still not clear if I want to have 
       # right alt serve as the ctrl key.
       # ref:  setxkbmap -option ctrl:swap_lalt_lctl
       # Also checking out what keyboard options are set is done with
       # setxkbmap -query
       # To get the list of available switches: man xkeyboard-config
       # To unset all the options
       # setxkbmap -option 
       # Reference for trying to get left alt act as lctrl without swapping
       #  https://unix.stackexchange.com/questions/353490/map-right-alt-to-left-control
    - name: Modify bashrc to have local bin files in the in path and capslock as ctrl
      blockinfile:
        path: "{{ HOME_USER_DIR }}/.bashrc"
        create: True
        block: |
          export PATH=$PATH:{{ LOCAL_BIN_PATH }}
          setxkbmap -option 
          setxkbmap -option ctrl:nocaps
          alias vi=nvim
