---
# Create the needed dirs
    - name: Create the home dir for app images if not there
      file:
       path: "{{ LOCAL_APPIMAGE_PATH }}"
       state: directory
       mode: 0755

    - name: Create "{{ LOCAL_BIN_PATH }}" if not there
      file:
       path: "{{ LOCAL_BIN_PATH }}"
       state: directory
       mode: 0755

    - name: Create "{{ LOCAL_DOT_CONFIG_PATH }}" if not there
      file:
       path: "{{ LOCAL_DOT_CONFIG_PATH }}"
       state: directory
       mode: 0755

    - name: Export local bin to path
      blockinfile:
        path: "{{ HOME_USER_DIR }}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK [local_dirs]"
        create: True
        block: |
          export PATH=$PATH:{{ LOCAL_BIN_PATH }}

    - name: Set var to trim prompt size
      blockinfile:
        path: "{{ HOME_USER_DIR }}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK [local_dirs]"
        create: True
        block: |
          PROMPT_DIRTRIM=2
