---
# Create the needed dirs
    - name: Create the home dir for app images if not there
      file:
       path: "{{ LOCAL_APPIMAGE_PATH }}"
       state: directory
       mode: 0755

    - name: Create "{{ LOCAL_BIN_PATH }}" if not there
      file:
       path: "{{ LOCAL_BIN_PATH }}"
       state: directory
       mode: 0755
    
    - name: Create "{{ LOCAL_DOT_CONFIG_PATH }}" if not there
      file:
       path: "{{ LOCAL_DOT_CONFIG_PATH }}"
       state: directory
       mode: 0755

    - name: Modify bashrc to have local bin files in the in path and capslock as ctrl
      blockinfile:
        path: "{{ HOME_USER_DIR }}/.bashrc"
        create: True
        block: |
          export PATH=$PATH:{{ LOCAL_BIN_PATH }}
          setxkbmap -option ctrl:nocaps
