---

- name: Install Node.js 
  apt:
    name: nodejs
    state: present
  become: true

- name: Install npm 
  apt:
    name: npm
    state: present
  become: true

- name: Install basedpyright globally
  npm:
    name: basedpyright
    global: true

