---
# roles/set_keymaps/tasks/main.yml
# Only tasks: no top-level play or "hosts" statements.

- name: Ensure dconf is installed
  become: true
  apt:
    name: dconf-cli
    state: present

- name: Set Caps Lock to Control (GNOME Wayland)
  become: false
  command: >
    gsettings set org.gnome.desktop.input-sources xkb-options "['ctrl:nocaps']"
  changed_when: true

- name: Verify the setting
  become: false
  command: >
    gsettings get org.gnome.desktop.input-sources xkb-options
  register: gsettings_output
  changed_when: false

- name: Debug output
  debug:
    msg: "{{ gsettings_output.stdout }}"
